language: node_js
node_js:
- 8
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: DlcpS1hQj8xrJ/AYqBrvJHZTXQnjTjGUtr/to2y7ZuhEFgcj0wTSI+zAeyj/01Kp8lXwf9U/rqZ01EVvNkCxDd6MLLUZH0UMjVwDocZlGeGW1wzH7aJFzjW98YLgkTnCaJn2BqCpPovN0NNtjTx85BJYCjMbbEKzy9XRlUfrHiankZNeAXfOh7ES5d01nGmFwYhpr9rbv2Ljzt373bXMpDvSWKRUk6hWqtaeUaY8yDxiY/tIkbKU1Zze7GwEtX4bZJyi84AblDhW62/sJtMTSvCd0tL0g9j310c8FzONYM+jMee52ZLy8NnKGVKVH4mWZiT18YUPqOe8R2FuNl5haEeS05Ciq0gSicLBfVg0Kla3TfWWRwTdS13MqXWcR9oYOjhuMLKb9FIp8CgUT3znrHXnpcqsw7EblmbXr2x75I+QtKRGDzytq1oFST6UCw24JLCSCD28SiS0GBuW+RZFjEIwTNzIO9GfwYx/GBLK8zO5JbgivlivI0IM9XvCB/ai7rm3VcnJEPOwCKQMkB8PajiBuBK32Gs7bqnBOmGrBF6us0H4aukZGKX2GXaIeq7dz+RNKoMNYoycJvGZ+3QdtFZtiBIydJHDUcXCag8gd+4ENlD28YKP8T1UjXn04bdhdgn31oMFeFEQ6uWRWSaXAfi1zm+3OjFEawTbzHdgsno=
  project: "bloglist-384cc"
cache:
  directories:
    - "node_modules"
script:
  - npm run build
