language: node_js
node_js:
- 8
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: DlcpS1hQj8xrJ/AYqBrvJHZTXQnjTjGUtr/to2y7ZuhEFgcj0wTSI+zAeyj/01Kp8lXwf9U/rqZ01EVvNkCxDd6MLLUZH0UMjVwDocZlGeGW1wzH7aJFzjW98YLgkTnCaJn2BqCpPovN0NNtjTx85BJYCjMbbEKzy9XRlUfrHiankZNeAXfOh7ES5d01nGmFwYhpr9rbv2Ljzt373bXMpDvSWKRUk6hWqtaeUaY8yDxiY/tIkbKU1Zze7GwEtX4bZJyi84AblDhW62/sJtMTSvCd0tL0g9j310c8FzONYM+jMee52ZLy8NnKGVKVH4mWZiT18YUPqOe8R2FuNl5haEeS05Ciq0gSicLBfVg0Kla3TfWWRwTdS13MqXWcR9oYOjhuMLKb9FIp8CgUT3znrHXnpcqsw7EblmbXr2x75I+QtKRGDzytq1oFST6UCw24JLCSCD28SiS0GBuW+RZFjEIwTNzIO9GfwYx/GBLK8zO5JbgivlivI0IM9XvCB/ai7rm3VcnJEPOwCKQMkB8PajiBuBK32Gs7bqnBOmGrBF6us0H4aukZGKX2GXaIeq7dz+RNKoMNYoycJvGZ+3QdtFZtiBIydJHDUcXCag8gd+4ENlD28YKP8T1UjXn04bdhdgn31oMFeFEQ6uWRWSaXAfi1zm+3OjFEawTbzHdgsno=
  project: bloglist-384cc
cache:
  directories:
  - node_modules
script:
- npm run build
env:
  global:
    secure: IXEmKvgSGohDkrAjrSCQV61jL+hFO7+6VyINcN+0u1Gk0jBkdXZrwAHhuC1rwYSGiKFnpm8S/Y737yqw19SoiuEFZBFnsW8ZE3VFIcleVQfHBjMNc4wSOz5kqHjygmNb30nv8tduriVsUiNsUT2NCO6IEO5a1AUSVWg1geQp0ICzw84sudatMAphIxxbeBSIkFfBj6sBv6zekbh94QANVu4rwLTEYaJVf4n6HxEflz1itC7lzqh+cHTkATDgL1R4KV9+bpokh3rew9IKyV9LmWXhHD4T8KZm4HsbDbMZUW9/BEw4isV1jyzdULmoWNcnYrV+k6hZa3xt4P3gpSEPpIiPepVmC5kunkYdvO8At1oisauA5IZvzb0xxieldB8+ZxckjEHfZ6RsOh1ILH/sJgSswVaHOPRY8+KmNCKLzFCGNln3N0UYw/eueKOq13EjG2xzsz40fj/la9NFQ+Zc/9P57pX5VVUEFcB6fE/1RGWnbRVbE3/f+kRjazdQRRpADB2BX+yFS7QwdHXLaBkH4UgaZ/fYz3Pxsybf4aHO8eQ6ERH8EvcxGZ1hOAFryMaMh4j3TaxQjnD9AAIqvOTsCyUr1wHf8KwLiZMlhuYT0QVGx7qF62QBNiBNIUVLJkCQyhWmOQfU/W1JuhCiJiud/xzBcyOaAi5gLKSHDLv/VAY=
